[package]
name = "pingora-guide"
version = "0.1.0"
edition = "2024"

[lib]
name = "pingora_guide"
path = "src/lib.rs"

[[bin]]
name = "pingora-guide"
path = "src/main.rs"

[dependencies]
pingora = { version = "0.6.0", features = ["openssl", "proxy", "lb", "cache"] }
pingora-load-balancing = { version = "0.6.0", features = ["openssl"]}
pingora-limits = { version = "0.6.0"}
pingora-cache = { version = "0.6.0" }

tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
futures-util = "0.3.31"
async-trait = "0.1.89"
bytes = "1.11.0"
http = "1.4.0"
once_cell = "1.21.3"

log = "0.4.29"
env_logger = "0.11.8"

# Must match the version of prometheus pingora was built with, otherwise you will come into a registry issue.
# cargo tree -p pingora | grep prometheus
prometheus = "0.13.4"

clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
humantime-serde = "1.1.1"
serde_yaml = "0.9"
serde_json = { version = "1.0.149"}
matchit = "0.9.1"
regex = "1.12.2"
uuid = { version = "1.19.0", features = ["fast-rng", "v4"]}

thiserror = "2.0.17"
chrono = "0.4.42"
num_cpus = "1.17.0"
ipnet = { version = "2.11.0" }

